name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Exercise
      id: exercise
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Exercise
        setup-command: ''
        command: mvn clean verify
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        EXERCISE_RESULTS: "${{steps.exercise.outputs.result}}"
      with:
        runners: exercise
